# Generated by Django 4.1.6 on 2023-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='created_at',
        ),
    ]
